#!/usr/bin/python3
import sys
from primes import factor, primef

if __name__ == "__main__":
    lpi = []
    with open(sys.argv[1], 'r') as file:
        lines = file.readlines()
        for line in lines:
            lpi.append(int(line))
    for i in lpi:
        j = factor(i)
        print("{}={:d}*{}".format(i,int(i/j),j))

