#!/usr/bin/python3
import sys
from prime import factor, primef
lp = []
with open("prime.txt", 'r') as file:
        for line in file:
            lp=line[:-1].split(",")
            break
lp = list(map(int, lp))
if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)
    lpi = []
    with open(sys.argv[1], 'r') as file:
        for line in file:
            i = int(line[:-1])
        j = factor(i,lp)
        print("{}={:d}*{}".format(i,i//j,j))