#!/usr/bin/python3
import sys
from prime import factor, primef, isprime, factors_1
if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)
    lpi = []
    with open(sys.argv[1], 'r') as file:
        lines = file.readlines()
        for line in lines:
            lpi.append(int(line))
    for i in lpi:
        l = factors_1(i)
        if len(l) == 2:
            j = 1
        else:
            for k in l:
                if k != 1 and k != i:
                    j = k
        print("{}={:d}*{}".format(i,i//j,j))