#!/usr/bin/python3
import sys
from prime import factor, primef
if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)
    lpi = []
    with open(sys.argv[1], 'r') as file:
        for i in file:
            n = int(i[:-1])
            j = factor(n)
            print("{}={:d}*{}".format(n,n//j,j))
